### ISSUE TITLE
Suggestion: add path_to_parse to the example_lab_and_model_settings in dr2xml.py

### ISSUE THREAD

**Issue by treerink** [senesis/dr2pub#13]
I think it would be handy if the **_path_to_parse_** variable will be added to the **_example_lab_and_model_settings_** in **_dr2xml.py_**, it makes it easier to find the correct way to set this basic path. Thus I suggest to add a line like: 
````shell
     'path_to_parse': "./",  # The path of the directory which contains the iodef.xml, field_def, etc. files.
````

**Comment by senesis** [comment]
Right. Next version will include that
